### PR TITLE
Updated max limit to 10,000

### PR DESCRIPTION
**Pull request by mikaylamurphy**
API now apparently allows you to pull up to 10,000 data points at once, according to Python wrapper

### CODE REVIEW

**Comment by masalmon** [comment]
Thanks, I had missed this. @jflasher in the API doc it seems to be 1000 for e.g. measurements, is the limit different depending on the endpoint?

**Comment by masalmon** [comment]
@mikaylamurphy please dont change the html, I generate them automatically with pkgdown 😉 the doc only needs to be updated in vignette, readme and .R.

Once I get Joe's answer I'll merge your PR. Can you add yourself as "ctb" i.e.contributor in DESCRIPTION?

**Comment by mikaylamurphy** [comment]
Gotcha, we weren't sure if the html files were automatically generated or not. 

We were able to pull 10,000 measurements using the updated R package, so we're thinking it's just a typo in the measurements API documentation.

I'll add myself now and update the vignette. Thanks for the update!

**Comment by masalmon** [comment]
Great,I'll have a look later today then. Thanks again. If there are two of you (you say "we") you can add both of you as ctb 😉

**Comment by masalmon** [comment]
Ok so now PR is merged + package NEWS and version updated, many thanks @mikaylamurphy :ok_hand:

**Pull request merged**
